name: Run SBT tests
on: 
  push:
    paths:
      - 'backend/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
      - name: Pull python image for tests
        run: docker pull python:3-alpine
      - name: Pull rocker image for tests
        run: docker pull rocker/r-base:4.1.3
      - name: Build and Test
        run: sbt -v +test
        working-directory: ./backend
